apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-mongo
  template:
    metadata:
      labels:
        app: posts-mongo
    spec:
      containers:
        - name: posts-mongo
          image: mongo
          # image: gcr.io/ticketing-dev-305621/posts
          # resources:
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: posts-mongo-clusterip-service
spec:
  selector:
    app: posts-mongo
  type: ClusterIP
  ports:
    - name: posts-mongo-db
      protocol: TCP
      port: 27017 # default port that mongo is listening to.
      targetPort: 27017
