apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/**/*

build:
  local:
    push: false
  artifacts:
    - image: cdub/rb6art-auth
      context: packages/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: cdub/rb6art-client
      context: packages/client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
          - src: '**/*.tsx'
            dest: .
    - image: cdub/rb6art-posts
      context: packages/posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
# This config is used if you want to use google cloud..
# build:
#   googleCloudBuild:
#     projectId: ticketing-dev-305621
#   artifacts:
#     - image:  gcr.io/ticketing-dev-305621/auth
#       context: auth
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - src: 'src/**/*.ts'
#             dest: .

